# Author: Rafshan Ul Atik
# Date: 2022
# Email: rafshanulatik@gmail.com

#!/usr/bin/bash

# loop through SCF files generated by phonopy
for i in {001..384}
do
    # create a directory with name "dis-<number>"
    mkdir dis-$i
    
    # move file "POSCAR-<number>" to directory "dis-<number>"
    mv POSCAR-$i dis-$i/POSCAR
    
    # copy files {POTCAR, INCAR, KPOINTS, job.sh} to directory "dis-<number>"
    cp {POTCAR,INCAR,KPOINTS,job.sh} dis-$i/
    
    # submit job script "dis-<number>/job.sh" using the qsub command
    # change the number of files to be submitted at once according to the
    # limit set by your cluster.
    if [ $i -ge 001 ] && [ $i -le 010 ]
    then
        qsub dis-$i/job.sh
    fi
done


